### ISSUE TITLE
ConfigValues missing entries

### ISSUE THREAD

**Issue by z3r0c00l2005** [mattolan/RT_OD#1]
when trying to run the current codebase it is apparent that the ConfigValues fle is missing entries for AlertObjectType and FaceDetectionEnabled

**Comment by mattolan** [comment]
Thank you, you are correct I missed updating the ConfigValuesTemplate.py file with a couple of parameter.  It should be corrected now.

**Comment by dallasweitzel** [comment]
I installed all the modules and this popped up when running the code.

Traceback (most recent call last):
  File "C:\Users\dalla\Source\Repos\RT_OD\RT_OD.py", line 14, in <module>
    from SMS import Send_SMS
  File "C:\Users\dalla\Source\Repos\RT_OD\SMS.py", line 4, in <module>
    import ConfigValues
ModuleNotFoundError: No module named 'ConfigValues'
Press any key to continue . . .
