### ISSUE TITLE
dropbox with twilio

### ISSUE THREAD

**Issue by AznRaven** [mattolan/RT_OD#2]
i was able to upload a photo to dropbox and get the link but was unable to use the photo link to send a mms through twilio. is there something special i need to do to the dropbox link in order to pass it to twilio? thank you

**Comment by mattolan** [comment]
Twilio is a paid service.  Did you setup a Twilio account?  Once you have your account setup you have to enter your account info in the ConfigValues files Lines 12 through 17

Then enter an alert destination on line 41 (your cell phone \ s)

**Comment by AznRaven** [comment]
thank you!!!

**Comment by mattolan** [comment]
your welcome
